#!/usr/bin/env bash


if [[ -z $1 ]]; then
    rcfile="rc.lua"
else
    rcfile="$1"
fi

Xephyr -ac -br -noreset -screen 1024x768 :1.0 &
ZEPHYR_PID=$!
sleep 1
DISPLAY=:1.0 awesome -c ~/.config/awesome/$rcfile
kill $ZEPHYR_PID

